from __future__ import annotations

from app_core.infrastructure.foc_reconstruction.foc_sources import utc_now


def _table_entry(
    *,
    label: str,
    caption: str,
    scientific_purpose: str,
    source_module: str,
    source_json_file: str,
    required_repetition_level: str,
    metrics_required: list[str],
    support_status: str,
    limitations: list[str],
    reviewer_concern_addressed: str,
) -> dict:
    return {
        "table_label": label,
        "table_caption": caption,
        "scientific_purpose": scientific_purpose,
        "source_module": source_module,
        "source_json_file": source_json_file,
        "required_repetition_level": required_repetition_level,
        "metrics_required": metrics_required,
        "current_support_status": support_status,
        "limitations": limitations,
        "reviewer_concern_addressed": reviewer_concern_addressed,
    }


def build_paper_table_registry(
    *,
    level: str,
    level_a_available: bool,
    level_a_report_path: str | None = None,
    level_b_available: bool = False,
    level_b_report_path: str | None = None,
) -> dict:
    rows = [
        _table_entry(
            label="TAB-QUAL-POSITIONING",
            caption="Qualitative positioning of the framework and its scientific validation scope.",
            scientific_purpose="Explain architecture and methodological scope without runtime overclaiming.",
            source_module="foc_paper_evidence.audit",
            source_json_file="paper_evidence_manifest.json",
            required_repetition_level="design_mapping",
            metrics_required=["view capabilities", "backend coverage", "generated artifacts"],
            support_status="supported",
            limitations=["Architecture mapping does not by itself prove runtime repeatability."],
            reviewer_concern_addressed="Clarifies what the system is intended to measure and what each module contributes.",
        ),
        _table_entry(
            label="TAB-REQ-METRIC-MAP",
            caption="Mapping between manuscript requirements and operational metrics.",
            scientific_purpose="Show that requirements are operationalized as concrete runtime indicators.",
            source_module="foc_paper_evidence.tables",
            source_json_file="paper_table_registry.json",
            required_repetition_level="design_mapping",
            metrics_required=["CPR", "WCPR", "integrity", "temporal confidence", "claimability", "latency"],
            support_status="supported",
            limitations=[],
            reviewer_concern_addressed="Addresses reviewer concern that invariants and requirements were not operationalized.",
        ),
        _table_entry(
            label="TAB-LEVEL-A-REPEATABILITY",
            caption="Level A analytical repeatability over the same preserved case.",
            scientific_purpose="Demonstrate whether the same preserved evidence yields stable analytical outputs across repeated reanalysis runs.",
            source_module="foc_paper_evidence.service",
            source_json_file=level_a_report_path or "level_a_report.json",
            required_repetition_level="A",
            metrics_required=["CPR per repetition", "WCPR per repetition", "delta CPR", "delta WCPR", "support-rank shift", "conclusion stability"],
            support_status="supported" if level_a_available else "unsupported",
            limitations=[] if level_a_available else ["A valid Level A report has not been generated yet."],
            reviewer_concern_addressed="Addresses whether results are stable without changing the preserved evidence.",
        ),
        _table_entry(
            label="TAB-DIAGNOSTIC-INDICATORS",
            caption="Diagnostic indicators separating artifact availability, analysis usefulness, causal strength, temporal confidence, integrity coverage, and claimability.",
            scientific_purpose="Prevent circular validation by separating technical completion from causal and scientific support.",
            source_module="foc_paper_evidence.service",
            source_json_file="paper_metrics_summary.json",
            required_repetition_level="A_or_B_or_C",
            metrics_required=["artifact availability", "analysis usefulness", "CPR", "WCPR", "temporal confidence", "integrity ratio", "claimability class"],
            support_status="supported" if level_a_available else "partial",
            limitations=["Level A supports diagnostic separation for one preserved case and its repeated reanalysis, but not incident-to-case acquisition variability."],
            reviewer_concern_addressed="Addresses reviewer concern that 100% operational readiness was being conflated with complete causal reconstruction.",
        ),
        _table_entry(
            label="TAB-RELATION-STATE-MATRIX",
            caption="Recovered, degraded, ambiguous, and missing causal relations with situational meaning.",
            scientific_purpose="Show what each missing or degraded relation means in forensic terms rather than hiding it behind a single scalar score.",
            source_module="foc_paper_evidence.service",
            source_json_file="level_a_report.json",
            required_repetition_level="A_or_B_or_C",
            metrics_required=["edge_id", "source_event", "target_event", "required_evidence", "support_status", "degradation_reason", "temporal_resolvability"],
            support_status="supported" if level_a_available else "partial",
            limitations=["Level A can document the relation-state matrix for the preserved case, but Level B or C are required to show how those relations behave across newly acquired cases."],
            reviewer_concern_addressed="Addresses reviewer concern that abstract counts of recovered/degraded/missing relations lack operational and forensic meaning.",
        ),
        _table_entry(
            label="TAB-OPER-LATENCY",
            caption="Operational trigger-to-acquisition latency metrics.",
            scientific_purpose="Quantify alert-driven acquisition latency and preservation ordering.",
            source_module="foc_paper_evidence.service",
            source_json_file=level_b_report_path or "level_b_report.json",
            required_repetition_level="B",
            metrics_required=["alert_to_memory_start", "alert_to_case_sealed", "layer ordering trace"],
            support_status="supported" if level_b_available else "unsupported",
            limitations=[] if level_b_available else ["Requires real Level B repeated incident executions and new forensic cases."],
            reviewer_concern_addressed="Addresses reviewer concern that operational latency and trigger effectiveness were not quantified.",
        ),
        _table_entry(
            label="TAB-ARTIFACT-SIZE-COVERAGE",
            caption="Artifact counts, sizes, and coverage by layer.",
            scientific_purpose="Show what was preserved and how complete the evidence set is.",
            source_module="foc_paper_evidence.service",
            source_json_file="paper_metrics_summary.json",
            required_repetition_level="A_or_B",
            metrics_required=["inventory counts", "artifact categories", "integrity coverage"],
            support_status="supported" if level_a_available else "partial",
            limitations=["Level A can support preserved artifact inventory, but Level B is required for new-case acquisition coverage statistics."],
            reviewer_concern_addressed="Addresses whether evidence preservation and coverage are measurable rather than assumed.",
        ),
        _table_entry(
            label="TAB-FAILURE-DEGRADATION",
            caption="Observed degraded, partial, missing, or unsupported states.",
            scientific_purpose="Avoid circular 100% success narratives and make limitations explicit.",
            source_module="foc_paper_evidence.service",
            source_json_file="paper_limitations_report.json",
            required_repetition_level="A_or_B_or_C",
            metrics_required=["degraded edges", "missing edges", "partial integrity", "timestamp limitations", "fallback trigger"],
            support_status="supported" if level_a_available else "partial",
            limitations=["Current output reflects observed degradation in real artifacts; it does not claim a complete controlled fault-injection campaign."],
            reviewer_concern_addressed="Directly addresses the reviewer concern about hidden failures and perfect binary success narratives.",
        ),
        _table_entry(
            label="TAB-INVARIANT-RECOVERY",
            caption="Operationalization of manuscript invariants or relation-recovery requirements.",
            scientific_purpose="Show which manuscript invariants are backed by runtime evidence, which are only design-mapped, and which remain unsupported.",
            source_module="foc_paper_evidence.service",
            source_json_file="paper_table_registry.json",
            required_repetition_level="A_or_B_or_C",
            metrics_required=["requirements-to-metrics mapping", "runtime source artifact", "support status"],
            support_status="partial",
            limitations=["The current runtime package operationalizes relation recovery, diagnostic indicators, and support classes. If the paper uses named invariants such as C1-C5, they still need an explicit manuscript-to-runtime mapping file."],
            reviewer_concern_addressed="Addresses reviewer concern that semantic or forensic invariants were claimed without a concrete runtime operationalization trace.",
        ),
        _table_entry(
            label="TAB-LEVEL-B-COMPARABILITY",
            caption="Cross-case comparability under repeated incident execution in the same scenario.",
            scientific_purpose="Show whether new cases created from repeated executions remain forensically comparable.",
            source_module="foc_paper_evidence.service",
            source_json_file=level_b_report_path or "level_b_report.json",
            required_repetition_level="B",
            metrics_required=["cross-case CPR/WCPR", "trigger quality", "artifact coverage", "claimability stability"],
            support_status="supported" if level_b_available else "unsupported",
            limitations=[] if level_b_available else ["Requires Level B paper evidence execution over new repeated cases."],
            reviewer_concern_addressed="Addresses reviewer concern that repeatability must include acquisition and preservation, not just reanalysis.",
        ),
        _table_entry(
            label="TAB-LEVEL-C-REDEPLOYMENT",
            caption="Redeployment-aware reproducibility after full scenario teardown and rebuild.",
            scientific_purpose="Measure infrastructure-level reproducibility rather than only analytical repeatability.",
            source_module="foc_paper_evidence.service",
            source_json_file="level_c_report.json",
            required_repetition_level="C",
            metrics_required=["deployment time", "scenario drift", "topology drift", "tool-version drift", "forensic comparability"],
            support_status="unsupported",
            limitations=["Level C paper evidence path is not yet implemented."],
            reviewer_concern_addressed="Addresses reviewer concern about full reproducibility beyond one deployment state.",
        ),
    ]
    return {
        "generated_at": utc_now(),
        "scope": f"paper_table_registry_level_{level.lower()}",
        "rows": rows,
    }
