from __future__ import annotations

from typing import Any, Dict, List, Optional


def _attack(**kwargs: Any) -> Dict[str, Any]:
    attack = {
        "attack_id": "",
        "legacy_name": "",
        "display_name": "",
        "category": "",
        "description": "",
        "mitre_domain": "",
        "mitre_id": "",
        "mitre_technique": "",
        "tactic": "",
        "detection_engine": "",
        "target_roles": [],
        "severity": "LOW",
        "execution_mode": "controlled",
        "script": "",
        "expected_alerts": [],
        "expected_artifacts": [],
        "safety_policy": "",
        "rollback_required": False,
        "dfir_escalation": False,
        "ui_section": "existing",
        "launch_enabled": True,
        "parameters_schema": {},
        "card_badges": [],
        "aliases": [],
        "execution_backend": "remote",
    }
    attack.update(kwargs)
    attack["target_roles"] = [str(role).lower() for role in attack["target_roles"]]
    return attack


ATTACK_CATALOG: List[Dict[str, Any]] = [
    _attack(
        attack_id="T1595_ACTIVE_SCANNING_ICMP_RECON",
        legacy_name="ICMP RECONNAISSANCE",
        display_name="ICMP Reconnaissance",
        category="Reconnaissance",
        description="Controlled ICMP-based reconnaissance to verify reachability of selected CyberLab targets.",
        mitre_domain="Enterprise",
        mitre_id="T1595",
        mitre_technique="Active Scanning",
        tactic="Reconnaissance",
        detection_engine="Suricata + Wazuh",
        target_roles=["victim", "monitor", "plc", "scada"],
        severity="LOW",
        execution_mode="controlled",
        script="ping_target.sh",
        expected_alerts=["icmp_sweep", "host_discovery", "active_scanning"],
        expected_artifacts=["pcap", "suricata_eve_json", "wazuh_alert", "execution_log"],
        safety_policy="Only internal CyberLab targets are allowed.",
        ui_section="existing",
        aliases=["recon_icmp"],
    ),
    _attack(
        attack_id="T1046_NETWORK_SERVICE_DISCOVERY_PORT_SCAN",
        legacy_name="PORT SCAN RECONNAISSANCE",
        display_name="Port Scan Reconnaissance",
        category="Reconnaissance",
        description="Controlled port scan to identify exposed services on selected CyberLab targets.",
        mitre_domain="Enterprise",
        mitre_id="T1046",
        mitre_technique="Network Service Discovery",
        tactic="Discovery",
        detection_engine="Suricata + Wazuh",
        target_roles=["victim", "monitor", "plc", "scada"],
        severity="MEDIUM",
        execution_mode="controlled",
        script="port_scan_recon.sh",
        expected_alerts=["port_scan", "network_service_discovery", "service_probe"],
        expected_artifacts=["pcap", "scan_output", "suricata_eve_json", "wazuh_alert", "execution_log"],
        safety_policy="Use a small allowlisted port list only.",
        ui_section="existing",
        aliases=["recon_portscan"],
    ),
    _attack(
        attack_id="T1110_001_SSH_PASSWORD_GUESSING",
        legacy_name="UNAUTHORIZED SSH ATTEMPT",
        display_name="Unauthorized SSH Attempt",
        category="Unauthorized Access",
        description="Controlled failed SSH login attempts using lab-defined invalid credentials.",
        mitre_domain="Enterprise",
        mitre_id="T1110.001",
        mitre_technique="Password Guessing",
        tactic="Credential Access",
        detection_engine="Wazuh",
        target_roles=["victim", "scada"],
        severity="MEDIUM",
        execution_mode="detection_validation",
        script="unauthorized_ssh_attempt.sh",
        expected_alerts=["failed_ssh_login", "multiple_authentication_failures", "ssh_bruteforce_validation"],
        expected_artifacts=["auth_log_extract", "wazuh_alert", "attempt_sequence", "execution_log"],
        safety_policy="Use a small number of failed attempts only. No real password lists.",
        ui_section="existing",
        aliases=["credential_unauthorized_ssh"],
        parent_mitre_id="T1110",
        parent_mitre_technique="Brute Force",
    ),
    _attack(
        attack_id="T1565_001_STORED_DATA_MANIPULATION_FIM",
        legacy_name="CONTROLLED FILE TAMPER",
        display_name="Controlled File Tamper",
        category="Integrity / FIM",
        description="Controlled modification of a monitored lab file to validate Wazuh file integrity monitoring and forensic evidence preservation.",
        mitre_domain="Enterprise",
        mitre_id="T1565.001",
        mitre_technique="Stored Data Manipulation",
        tactic="Impact",
        detection_engine="Wazuh FIM",
        target_roles=["victim", "scada"],
        severity="HIGH",
        execution_mode="controlled",
        script="file_tamper_sim.sh",
        expected_alerts=["file_modified", "fim_integrity_alert", "stored_data_manipulation"],
        expected_artifacts=["hash_before", "hash_after", "file_metadata_before", "file_metadata_after", "wazuh_fim_alert", "execution_log"],
        safety_policy="Modify only lab-created files under /tmp/nics_attack_lab/fim.",
        rollback_required=False,
        dfir_escalation=True,
        ui_section="existing",
        aliases=["impact_file_tamper"],
    ),
    _attack(
        attack_id="T1048_EXFILTRATION_OVER_ALTERNATIVE_PROTOCOL",
        legacy_name="DATA EXFILTRATION",
        display_name="Data Exfiltration",
        category="Exfiltration",
        description="Controlled transfer of lab-generated data from a target node to an attacker-controlled node using an alternative protocol such as SCP.",
        mitre_domain="Enterprise",
        mitre_id="T1048",
        mitre_technique="Exfiltration Over Alternative Protocol",
        tactic="Exfiltration",
        detection_engine="Suricata + Wazuh",
        target_roles=["victim", "scada"],
        severity="HIGH",
        execution_mode="controlled",
        script="data_exfiltration.sh",
        expected_alerts=["outbound_file_transfer", "scp_transfer", "http_upload", "exfiltration_activity"],
        expected_artifacts=["source_file_hash", "destination_file_hash", "transfer_log", "pcap", "suricata_eve_json", "wazuh_alert", "execution_log"],
        safety_policy="Exfiltrate only lab-generated files under /tmp/nics_attack_lab.",
        dfir_escalation=True,
        ui_section="existing",
        aliases=["collection_data_exfiltration"],
    ),
    _attack(
        attack_id="T0831_MANIPULATION_OF_CONTROL_MODBUS",
        legacy_name="MODBUS REGISTER MANIPULATION",
        display_name="Modbus Register Manipulation",
        category="ICS / OT",
        description="Controlled manipulation of an allowed Modbus register to validate OT detection, process-state change tracking and forensic preservation.",
        mitre_domain="ICS",
        mitre_id="T0831",
        mitre_technique="Manipulation of Control",
        tactic="Impair Process Control",
        detection_engine="Suricata + Wazuh",
        target_roles=["plc", "scada"],
        severity="HIGH",
        execution_mode="restore_by_default",
        script="t0831_manipulation_of_control_modbus.py",
        expected_alerts=["modbus_write_register", "unauthorized_control_command", "process_state_change", "control_manipulation"],
        expected_artifacts=["plc_state_before", "plc_state_after", "modbus_transaction_log", "pcap", "suricata_eve_json", "wazuh_alert", "rollback_log", "forensic_case_event"],
        safety_policy="Only allow writes to predefined test registers. Rollback enabled by default.",
        rollback_required=True,
        dfir_escalation=True,
        ui_section="existing",
        aliases=["ics_modbus_register_write"],
        execution_backend="local",
    ),
    _attack(
        attack_id="CHAIN_MULTI_VECTOR_DETECTION_VALIDATION",
        legacy_name="MULTI-VECTOR VALIDATION",
        display_name="Multi-Vector Validation",
        category="Multi-Vector Exercise",
        description="Controlled multi-step validation scenario combining reconnaissance, unauthorized access attempts, file integrity manipulation, exfiltration and OT manipulation.",
        mitre_domain="Enterprise + ICS",
        mitre_id="MULTIPLE",
        mitre_technique="Composite ATT&CK Validation Chain",
        tactic="Multi-stage Detection Validation",
        detection_engine="Suricata + Wazuh",
        target_roles=["victim", "plc", "scada"],
        severity="HIGH",
        execution_mode="controlled_chain",
        script="multi_Attack_sim.sh",
        expected_alerts=["port_scan", "failed_ssh_login", "fim_integrity_alert", "exfiltration_activity", "modbus_write_register"],
        expected_artifacts=["pcap", "suricata_eve_json", "wazuh_alerts", "auth_log_extract", "fim_hashes", "transfer_log", "plc_state_before", "plc_state_after", "forensic_case_timeline"],
        safety_policy="Execute only inside CyberLab. Use lab files and allowed PLC registers only.",
        rollback_required=True,
        dfir_escalation=True,
        ui_section="existing",
        aliases=["validation_multi_vector"],
        chain_steps=[
            "T1046_NETWORK_SERVICE_DISCOVERY_PORT_SCAN",
            "T1110_001_SSH_PASSWORD_GUESSING",
            "T1565_001_STORED_DATA_MANIPULATION_FIM",
            "T1048_EXFILTRATION_OVER_ALTERNATIVE_PROTOCOL",
            "T0831_MANIPULATION_OF_CONTROL_MODBUS",
        ],
    ),
    _attack(
        attack_id="T1105_INGRESS_TOOL_TRANSFER",
        legacy_name="",
        display_name="Ingress Tool Transfer",
        category="Advanced Suricata-Detectable Techniques",
        description="Transfer a harmless marker file from attacker to target to validate network and file creation visibility.",
        mitre_domain="Enterprise",
        mitre_id="T1105",
        mitre_technique="Ingress Tool Transfer",
        tactic="Command and Control",
        detection_engine="Suricata + Wazuh",
        target_roles=["victim", "scada"],
        severity="MEDIUM",
        execution_mode="controlled",
        script="t1105_ingress_tool_transfer.sh",
        expected_alerts=["inbound_file_transfer", "new_file_creation", "network_transfer"],
        expected_artifacts=["pcap", "file_hash", "destination_file_metadata", "suricata_eve_json", "wazuh_fim_alert", "execution_log"],
        safety_policy="Do not transfer real offensive tools. Use only a harmless marker file.",
        ui_section="advanced_suricata",
    ),
    _attack(
        attack_id="T1570_LATERAL_TOOL_TRANSFER",
        legacy_name="",
        display_name="Lateral Tool Transfer",
        category="Advanced Suricata-Detectable Techniques",
        description="Move a harmless marker file from one internal node to another to emulate lateral movement.",
        mitre_domain="Enterprise",
        mitre_id="T1570",
        mitre_technique="Lateral Tool Transfer",
        tactic="Lateral Movement",
        detection_engine="Suricata + Wazuh",
        target_roles=["victim", "scada"],
        severity="MEDIUM",
        execution_mode="controlled",
        script="t1570_lateral_tool_transfer.sh",
        expected_alerts=["internal_file_transfer", "new_file_creation", "lateral_movement_validation"],
        expected_artifacts=["source_hash", "destination_hash", "pcap", "transfer_log", "timeline_event"],
        safety_policy="Only lab-generated files are allowed.",
        ui_section="advanced_suricata",
    ),
    _attack(
        attack_id="T0846_ICS_REMOTE_SYSTEM_DISCOVERY",
        legacy_name="",
        display_name="ICS Remote System Discovery",
        category="Advanced Suricata-Detectable Techniques",
        description="Discover PLC, SCADA, HMI and monitoring nodes inside the OT subnet.",
        mitre_domain="ICS",
        mitre_id="T0846",
        mitre_technique="Remote System Discovery",
        tactic="Discovery",
        detection_engine="Suricata + Wazuh",
        target_roles=["plc", "scada"],
        severity="MEDIUM",
        execution_mode="read_only",
        script="t0846_ics_remote_system_discovery.py",
        expected_alerts=["ot_subnet_probing", "remote_system_discovery", "suricata_scan_alert"],
        expected_artifacts=["discovered_hosts.json", "pcap", "suricata_alert", "wazuh_alert", "scan_output"],
        safety_policy="Only scan the OT lab subnet.",
        ui_section="advanced_suricata",
        execution_backend="local",
    ),
    _attack(
        attack_id="T0861_POINT_AND_TAG_IDENTIFICATION",
        legacy_name="",
        display_name="Point and Tag Identification",
        category="Advanced Suricata-Detectable Techniques",
        description="Read known lab Modbus registers to identify process variables such as level, pump state, valve state and setpoint.",
        mitre_domain="ICS",
        mitre_id="T0861",
        mitre_technique="Point and Tag Identification",
        tactic="Discovery",
        detection_engine="Suricata",
        target_roles=["plc", "scada"],
        severity="MEDIUM",
        execution_mode="read_only",
        script="t0861_point_and_tag_identification.py",
        expected_alerts=["modbus_read_burst", "register_enumeration", "suricata_modbus_alert"],
        expected_artifacts=["register_map.json", "read_register_log.json", "modbus_pcap", "suricata_modbus_alert", "case_timeline_event"],
        safety_policy="Read-only. No register writes.",
        ui_section="advanced_suricata",
        execution_backend="local",
    ),
    _attack(
        attack_id="T0802_AUTOMATED_COLLECTION",
        legacy_name="",
        display_name="Automated Collection",
        category="Advanced Suricata-Detectable Techniques",
        description="Collect short-window process-state samples from the tank PLC without modifying control values.",
        mitre_domain="ICS",
        mitre_id="T0802",
        mitre_technique="Automated Collection",
        tactic="Collection",
        detection_engine="Suricata + Wazuh",
        target_roles=["plc", "scada"],
        severity="MEDIUM",
        execution_mode="read_only",
        script="t0802_automated_collection.py",
        expected_alerts=["modbus_read_pattern", "process_state_collection", "suricata_modbus_alert"],
        expected_artifacts=["collection_session.jsonl", "collection_summary.json", "uncertainty_report.json"],
        safety_policy="Read-only collection over a short bounded sampling window.",
        ui_section="advanced_suricata",
        execution_backend="local",
    ),
    _attack(
        attack_id="T0877_IO_IMAGE",
        legacy_name="",
        display_name="I/O Image Acquisition",
        category="Advanced Suricata-Detectable Techniques",
        description="Read the current PLC input and output state to reconstruct the industrial process state.",
        mitre_domain="ICS",
        mitre_id="T0877",
        mitre_technique="I/O Image",
        tactic="Collection",
        detection_engine="Suricata",
        target_roles=["plc", "scada"],
        severity="MEDIUM",
        execution_mode="read_only",
        script="t0877_io_image.py",
        expected_alerts=["modbus_read_pattern", "io_image_acquisition", "suricata_modbus_alert"],
        expected_artifacts=["io_image_before.json", "io_image_after.json", "process_state_snapshot.json", "modbus_pcap", "suricata_alert"],
        safety_policy="Read-only by default.",
        ui_section="advanced_suricata",
        execution_backend="local",
    ),
    _attack(
        attack_id="T0836_MODIFY_PARAMETER",
        legacy_name="",
        display_name="Modify Parameter",
        category="Advanced Suricata-Detectable Techniques",
        description="Change a controlled industrial parameter such as a setpoint, alarm threshold, pump command or valve command.",
        mitre_domain="ICS",
        mitre_id="T0836",
        mitre_technique="Modify Parameter",
        tactic="Impair Process Control",
        detection_engine="Suricata + Wazuh",
        target_roles=["plc", "scada"],
        severity="HIGH",
        execution_mode="restore_by_default",
        script="t0836_modify_parameter.py",
        expected_alerts=["modbus_write", "parameter_change", "suricata_modbus_write", "wazuh_suricata_ingest"],
        expected_artifacts=["plc_state_before.json", "plc_state_after.json", "modbus_transaction_log.json", "pcap", "suricata_alert", "wazuh_alert", "rollback_log"],
        safety_policy="Use allowed registers only. Restore original value by default.",
        rollback_required=True,
        dfir_escalation=True,
        ui_section="advanced_suricata",
        execution_backend="local",
    ),
    _attack(
        attack_id="T1692_001_UNAUTHORIZED_COMMAND_MESSAGE",
        legacy_name="",
        display_name="Unauthorized Command Message",
        category="Advanced Suricata-Detectable Techniques",
        description="Send a controlled unauthorized Modbus command from attacker to PLC.",
        mitre_domain="ICS",
        mitre_id="T1692.001",
        mitre_technique="Unauthorized Command Message",
        tactic="Execution",
        detection_engine="Suricata + Wazuh",
        target_roles=["plc", "scada"],
        severity="HIGH",
        execution_mode="restore_by_default",
        script="t1692_001_unauthorized_command_message.py",
        expected_alerts=["unexpected_modbus_source", "unauthorized_modbus_write", "wazuh_suricata_ingest"],
        expected_artifacts=["source_ip", "destination_ip", "function_code", "register", "value", "modbus_pcap", "suricata_alert", "wazuh_alert", "plc_state_before.json", "plc_state_after.json"],
        safety_policy="Only allowed test registers. Rollback required.",
        rollback_required=True,
        dfir_escalation=True,
        ui_section="advanced_suricata",
        execution_backend="local",
    ),
    _attack(
        attack_id="T1078_VALID_ACCOUNTS_SSH_LOGIN",
        legacy_name="",
        display_name="Valid Accounts SSH Login",
        category="Advanced Wazuh-Detectable Techniques",
        description="Perform one controlled successful SSH login using a dedicated lab account.",
        mitre_domain="Enterprise",
        mitre_id="T1078",
        mitre_technique="Valid Accounts",
        tactic="Defense Evasion",
        detection_engine="Wazuh",
        target_roles=["victim", "scada"],
        severity="MEDIUM",
        execution_mode="controlled",
        script="t1078_valid_accounts_ssh_login.sh",
        expected_alerts=["successful_ssh_login", "remote_login", "auth_success"],
        expected_artifacts=["auth_log_success_entry", "wazuh_alert", "source_ip", "target_ip", "username", "command_output"],
        safety_policy="Use only dedicated lab credentials.",
        ui_section="advanced_wazuh",
    ),
    _attack(
        attack_id="T1082_SYSTEM_INFORMATION_DISCOVERY",
        legacy_name="",
        display_name="System Information Discovery",
        category="Advanced Wazuh-Detectable Techniques",
        description="Collect host information such as hostname, OS, kernel, architecture and uptime.",
        mitre_domain="Enterprise",
        mitre_id="T1082",
        mitre_technique="System Information Discovery",
        tactic="Discovery",
        detection_engine="Wazuh",
        target_roles=["victim", "monitor", "scada", "plc"],
        severity="LOW",
        execution_mode="read_only",
        script="t1082_system_information_discovery.sh",
        expected_alerts=["command_execution", "system_info_discovery"],
        expected_artifacts=["system_info.json", "command_stdout.txt", "execution_log", "timeline_event"],
        safety_policy="Read-only commands only.",
        ui_section="advanced_wazuh",
    ),
    _attack(
        attack_id="T1016_SYSTEM_NETWORK_CONFIGURATION_DISCOVERY",
        legacy_name="",
        display_name="System Network Configuration Discovery",
        category="Advanced Wazuh-Detectable Techniques",
        description="Collect network configuration such as IP addresses, routes, DNS and interfaces.",
        mitre_domain="Enterprise",
        mitre_id="T1016",
        mitre_technique="System Network Configuration Discovery",
        tactic="Discovery",
        detection_engine="Wazuh",
        target_roles=["victim", "monitor", "scada", "plc"],
        severity="LOW",
        execution_mode="read_only",
        script="t1016_system_network_configuration_discovery.sh",
        expected_alerts=["command_execution", "network_config_discovery"],
        expected_artifacts=["network_config.json", "ip_addr.txt", "ip_route.txt", "resolv_conf.txt", "execution_log"],
        safety_policy="Read-only commands only.",
        ui_section="advanced_wazuh",
    ),
    _attack(
        attack_id="T1049_SYSTEM_NETWORK_CONNECTIONS_DISCOVERY",
        legacy_name="",
        display_name="System Network Connections Discovery",
        category="Advanced Wazuh-Detectable Techniques",
        description="List active sockets and network connections.",
        mitre_domain="Enterprise",
        mitre_id="T1049",
        mitre_technique="System Network Connections Discovery",
        tactic="Discovery",
        detection_engine="Wazuh",
        target_roles=["victim", "monitor", "scada", "plc"],
        severity="LOW",
        execution_mode="read_only",
        script="t1049_system_network_connections_discovery.sh",
        expected_alerts=["command_execution", "network_connections_discovery"],
        expected_artifacts=["network_connections_before.txt", "network_connections_after.txt", "execution_log"],
        safety_policy="Read-only commands only.",
        ui_section="advanced_wazuh",
    ),
    _attack(
        attack_id="T1057_PROCESS_DISCOVERY",
        legacy_name="",
        display_name="Process Discovery",
        category="Advanced Wazuh-Detectable Techniques",
        description="List running processes and active services.",
        mitre_domain="Enterprise",
        mitre_id="T1057",
        mitre_technique="Process Discovery",
        tactic="Discovery",
        detection_engine="Wazuh",
        target_roles=["victim", "monitor", "scada", "plc"],
        severity="LOW",
        execution_mode="read_only",
        script="t1057_process_discovery.sh",
        expected_alerts=["command_execution", "process_discovery"],
        expected_artifacts=["process_list_before.txt", "process_list_after.txt", "execution_log"],
        safety_policy="Read-only commands only.",
        ui_section="advanced_wazuh",
    ),
    _attack(
        attack_id="T1033_SYSTEM_OWNER_USER_DISCOVERY",
        legacy_name="",
        display_name="System Owner or User Discovery",
        category="Advanced Wazuh-Detectable Techniques",
        description="Identify current user, UID, groups and logged-in users.",
        mitre_domain="Enterprise",
        mitre_id="T1033",
        mitre_technique="System Owner/User Discovery",
        tactic="Discovery",
        detection_engine="Wazuh",
        target_roles=["victim", "monitor", "scada", "plc"],
        severity="LOW",
        execution_mode="read_only",
        script="t1033_system_owner_user_discovery.sh",
        expected_alerts=["command_execution", "user_discovery"],
        expected_artifacts=["user_context.json", "logged_users.txt", "execution_log"],
        safety_policy="Read-only commands only.",
        ui_section="advanced_wazuh",
    ),
    _attack(
        attack_id="T1087_ACCOUNT_DISCOVERY",
        legacy_name="",
        display_name="Account Discovery",
        category="Advanced Wazuh-Detectable Techniques",
        description="Enumerate local accounts.",
        mitre_domain="Enterprise",
        mitre_id="T1087",
        mitre_technique="Account Discovery",
        tactic="Discovery",
        detection_engine="Wazuh",
        target_roles=["victim", "monitor", "scada", "plc"],
        severity="LOW",
        execution_mode="read_only",
        script="t1087_account_discovery.sh",
        expected_alerts=["command_execution", "account_discovery"],
        expected_artifacts=["account_list.txt", "execution_log"],
        safety_policy="Do not read /etc/shadow. Do not extract password hashes.",
        ui_section="advanced_wazuh",
    ),
    _attack(
        attack_id="T1083_FILE_AND_DIRECTORY_DISCOVERY",
        legacy_name="",
        display_name="File and Directory Discovery",
        category="Advanced Wazuh-Detectable Techniques",
        description="Search for interesting files and folders inside lab-created directories.",
        mitre_domain="Enterprise",
        mitre_id="T1083",
        mitre_technique="File and Directory Discovery",
        tactic="Discovery",
        detection_engine="Wazuh",
        target_roles=["victim", "scada"],
        severity="LOW",
        execution_mode="read_only",
        script="t1083_file_and_directory_discovery.sh",
        expected_alerts=["command_execution", "file_discovery"],
        expected_artifacts=["file_tree.txt", "discovered_files.json", "execution_log"],
        safety_policy="Search only under /tmp/nics_attack_lab.",
        ui_section="advanced_wazuh",
    ),
    _attack(
        attack_id="T1005_DATA_FROM_LOCAL_SYSTEM",
        legacy_name="",
        display_name="Data from Local System",
        category="Advanced Wazuh-Detectable Techniques",
        description="Collect fake sensitive lab data from local directories.",
        mitre_domain="Enterprise",
        mitre_id="T1005",
        mitre_technique="Data from Local System",
        tactic="Collection",
        detection_engine="Wazuh",
        target_roles=["victim", "scada"],
        severity="MEDIUM",
        execution_mode="controlled",
        script="t1005_data_from_local_system.sh",
        expected_alerts=["file_access", "collection_activity"],
        expected_artifacts=["collected_file_list.txt", "file_hashes_before.json", "collection_log.txt", "timeline_event"],
        safety_policy="Collect only lab-generated data.",
        ui_section="advanced_wazuh",
    ),
    _attack(
        attack_id="T1560_ARCHIVE_COLLECTED_DATA",
        legacy_name="",
        display_name="Archive Collected Data",
        category="Advanced Wazuh-Detectable Techniques",
        description="Compress collected lab files before exfiltration.",
        mitre_domain="Enterprise",
        mitre_id="T1560",
        mitre_technique="Archive Collected Data",
        tactic="Collection",
        detection_engine="Wazuh",
        target_roles=["victim", "scada"],
        severity="MEDIUM",
        execution_mode="controlled",
        script="t1560_archive_collected_data.sh",
        expected_alerts=["archive_creation", "file_created"],
        expected_artifacts=["archive_path", "archive_sha256", "archive_size", "file_manifest.json", "execution_log"],
        safety_policy="Archive only files under /tmp/nics_attack_lab.",
        ui_section="advanced_wazuh",
    ),
    _attack(
        attack_id="T1070_004_FILE_DELETION",
        legacy_name="",
        display_name="File Deletion",
        category="Advanced Wazuh-Detectable Techniques",
        description="Delete a lab-generated file to emulate anti-forensic deletion.",
        mitre_domain="Enterprise",
        mitre_id="T1070.004",
        mitre_technique="File Deletion",
        tactic="Defense Evasion",
        detection_engine="Wazuh FIM",
        target_roles=["victim", "scada"],
        severity="HIGH",
        execution_mode="controlled",
        script="t1070_004_file_deletion.sh",
        expected_alerts=["file_deleted", "fim_delete_alert"],
        expected_artifacts=["file_hash_before_delete", "deletion_timestamp", "wazuh_fim_alert", "execution_log"],
        safety_policy="Delete lab-generated files only.",
        dfir_escalation=True,
        ui_section="advanced_wazuh",
    ),
    _attack(
        attack_id="T1059_COMMAND_AND_SCRIPTING_INTERPRETER",
        legacy_name="",
        display_name="Command and Scripting Interpreter",
        category="Advanced Wazuh-Detectable Techniques",
        description="Run harmless command sequences through Bash or Python.",
        mitre_domain="Enterprise",
        mitre_id="T1059",
        mitre_technique="Command and Scripting Interpreter",
        tactic="Execution",
        detection_engine="Wazuh",
        target_roles=["victim", "monitor", "scada", "plc"],
        severity="MEDIUM",
        execution_mode="controlled",
        script="t1059_command_and_scripting_interpreter.sh",
        expected_alerts=["command_execution", "shell_invocation"],
        expected_artifacts=["command_line", "stdout", "stderr", "execution_timestamp", "process_metadata"],
        safety_policy="Only allow approved harmless commands.",
        ui_section="advanced_wazuh",
    ),
    _attack(
        attack_id="T1036_MASQUERADING",
        legacy_name="",
        display_name="Masquerading",
        category="Advanced Wazuh-Detectable Techniques",
        description="Create a harmless file with a misleading name in a lab directory.",
        mitre_domain="Enterprise",
        mitre_id="T1036",
        mitre_technique="Masquerading",
        tactic="Defense Evasion",
        detection_engine="Wazuh FIM",
        target_roles=["victim", "scada"],
        severity="MEDIUM",
        execution_mode="controlled",
        script="t1036_masquerading.sh",
        expected_alerts=["file_created", "masquerading_marker"],
        expected_artifacts=["file_path", "file_hash", "file_metadata", "wazuh_alert", "execution_log"],
        safety_policy="Do not place files in real system directories.",
        ui_section="advanced_wazuh",
    ),
    _attack(
        attack_id="T1027_OBFUSCATED_FILES_OR_INFORMATION",
        legacy_name="",
        display_name="Obfuscated Files or Information",
        category="Advanced Wazuh-Detectable Techniques",
        description="Encode a harmless marker string into Base64 and write it to a lab file.",
        mitre_domain="Enterprise",
        mitre_id="T1027",
        mitre_technique="Obfuscated Files or Information",
        tactic="Defense Evasion",
        detection_engine="Wazuh FIM",
        target_roles=["victim", "scada"],
        severity="MEDIUM",
        execution_mode="controlled",
        script="t1027_obfuscated_files_or_information.sh",
        expected_alerts=["file_created", "obfuscated_marker"],
        expected_artifacts=["cleartext_marker", "encoded_marker", "file_hash", "wazuh_alert", "execution_log"],
        safety_policy="No malware, payloads or credential material.",
        ui_section="advanced_wazuh",
    ),
    _attack(
        attack_id="T1562_001_DISABLE_OR_MODIFY_TOOLS_SIMULATED",
        legacy_name="",
        display_name="Disable or Modify Tools (Simulated)",
        category="Advanced Wazuh-Detectable Techniques",
        description="Simulate disabling a security tool by stopping a dummy monitoring service.",
        mitre_domain="Enterprise",
        mitre_id="T1562.001",
        mitre_technique="Disable or Modify Tools",
        tactic="Defense Evasion",
        detection_engine="Wazuh",
        target_roles=["victim", "monitor", "scada"],
        severity="HIGH",
        execution_mode="simulated",
        script="t1562_001_disable_or_modify_tools_simulated.sh",
        expected_alerts=["service_stop", "tool_disable_simulation"],
        expected_artifacts=["service_status_before.txt", "service_status_after.txt", "system_log_extract", "wazuh_alert", "execution_log"],
        safety_policy="Never stop real Wazuh, Suricata, SSH, OpenStack or CyberLab services by default.",
        dfir_escalation=True,
        ui_section="advanced_wazuh",
    ),
]


ATTACK_ALIASES: Dict[str, str] = {}
for _item in ATTACK_CATALOG:
    ATTACK_ALIASES[_item["attack_id"]] = _item["attack_id"]
    for _alias in _item.get("aliases", []):
        ATTACK_ALIASES[_alias] = _item["attack_id"]


def normalize_attack_id(attack_id: str) -> str:
    return ATTACK_ALIASES.get((attack_id or "").strip(), (attack_id or "").strip())


def get_attack_catalog(
    section: str = "",
    detection_engine: str = "",
    target_role: str = "",
) -> List[Dict[str, Any]]:
    normalized_section = (section or "").strip().lower()
    normalized_engine = (detection_engine or "").strip().lower()
    normalized_role = (target_role or "").strip().lower()

    attacks: List[Dict[str, Any]] = []
    for item in ATTACK_CATALOG:
        if normalized_section and item.get("ui_section", "").lower() != normalized_section:
            continue
        if normalized_engine and normalized_engine not in item.get("detection_engine", "").lower():
            continue
        if normalized_role and normalized_role not in item.get("target_roles", []):
            continue
        attacks.append(dict(item))
    return attacks


def find_attack_by_id(attack_id: str) -> Optional[Dict[str, Any]]:
    normalized = normalize_attack_id(attack_id)
    if not normalized:
        return None
    for item in ATTACK_CATALOG:
        if item["attack_id"] == normalized:
            return dict(item)
    return None


def find_attack_by_legacy_name(name: str) -> Optional[Dict[str, Any]]:
    needle = (name or "").strip().lower()
    if not needle:
        return None
    for item in ATTACK_CATALOG:
        if item.get("legacy_name", "").strip().lower() == needle:
            return dict(item)
    return None


def resolve_script_name(script_name: str = "", attack_id: str = "") -> Optional[str]:
    if script_name:
        return script_name
    attack = find_attack_by_id(attack_id)
    if attack:
        return attack["script"]
    return None
